displayName=Account History
author=maxcape
description=Tracks skill level ups and collection log entries and sends them to your account history server.
tags=skill,collection log,tracker,history
version=1.0.0
plugins=com.maxcape.accounthistory.AccountHistoryPlugin
build=standard
