displayName=MaxCape
author=josephmr
description=Tracks notable events like skill level ups and collection log entries and sends them to maxcape.net.
tags=skill,collection log,tracker,history,maxcape,max cape,account history
version=1.0.4
plugins=com.maxcape.accounthistory.AccountHistoryPlugin
build=standard
